# The Adorad Programming Language Syntax Metadata 

# Special (internal usage only) 
special = [
    "TOK_ID",
    "TOK_EOF",
    "TOK_NULL",
    "ILLEGAL",
    "COMMENT",
] # special

# Literals 
literals = [
    "IDENTIFIER",
    "INTEGER",
    "BIN_INT",
    "HEX_INT",
    "INT8_LIT",
    "INT16_LIT",
    "INT32_LIT",
    "INT64_LIT",
    "UINT_LIT",
    "UINT8_LIT",
    "UINT16_LIT",
    "UINT32_LIT",
    "UINT64_LIT",
    "FLOAT_LIT",
    "FLOAT32_LIT",
    "FLOAT64_LIT",
    "FLOAT128_LIT",
    "IMAG",
    "RUNE",
    "STRING",
    "RAW_STRING",
    "TRIPLE_STRING",
    "TRUE",
    "FALSE",
] # literals        

# Operators  
operators = [
    "+",
    "-",
    "*",
    "/",
    "%",
    "%%",
    "++",
    "--",
    "@",
    "#",
    "?",
   
    # Comparison Operators 
    ">",
    "<",
    ">=",
    "<=",
    "==",
    "!=",

    # Assignment Operators 
    "=",
    "+=",
    "-=",
    "*=",
    "/=",
    "%=",
    "&=",
    "|=",
    "^=",
    "<<=",
    ">>=",
    "~",

    # Arrows 
    "=>",
    "->",
    "<-",
   
    # Delimiters 
    "[",
    "]",
    "{",
    "}",
    "(",
    ")",
   
    # Bitwise Operators 
    "<<",
    ">>",
    "&",
    "|",
    "!",
    "^",
    "&^",
    "&&",
    "||",
] # operators 

# Separators 
separators = [
    ":",
    ";",
    ",",
    ".",
    "..",
    "...",
    "\\",
]

# Keywords 
keywords = [
    "any",
    "as",
    "begin",
    "break",
    "case",
    "cast",
    "catch",
    "const",
    "continue",
    "do",
    "decl",
    "default",
    "enum",
    "else",
    "elseif",
    "except",
    "export",
    "extern",
    "finally",
    "for",
    "from",
    "func",
    "if",
    "import",
    "in",
    "include",
    "inline",
    "isa",
    "macro",
    "map",
    "match",
    "module",
    "mutable",
    "noinline",
    "not",
    "notin",
    "raise",
    "range",
    "return",
    "struct",
    "try",
    "tuple",
    "type",
    "typeof",
    "use",
    "when",
    "where",
    "while",
    "union",
]