# This is a helpful build script with CMake <https://cristianadam.eu/20191222/using-github-actions-with-c-plus-plus-and-cmake/>
# We will switch to it, but at a later point in time. 

name: CI
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

# jobs:
#   test:
#     name: Test C
#     runs-on: ubuntu-latest

#     steps:
#       - name: LGTM
#         run: echo "LGTM" #TODO, uncomment
        
jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Hazel
        run: |
          mkdir build
          cmake -S . -B build
      # - name: Hazel run
      #   run: ./hazel run examples/demo/demo.hzl
      # - name: Hazel check
      #   run: ./hazel check examples/demo/demo.hzl -vet

  build_macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Hazel
        run: |
          mkdir build
          cmake -S . -B build
      # - name: Hazel run
      #   run: ./hazel run examples/demo/demo.hzl
      # - name: Hazel check
      #   run: ./hazel check examples/demo/demo.hzl -vet

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Hazel
        shell: cmd
        run: |
          mkdir build
          cmake -S . -B build
      # - name: Hazel run
      #   shell: cmd
      #   run: |
      #     call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
      #     hazel run examples/demo/demo.hzl
      # - name: Hazel check
      #   shell: cmd
      #   run: |
      #     call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
      #     hazel check examples/demo/demo.hzl -vet
